### ISSUE TITLE
multi sample import normalization and plot customisation.

### ISSUE THREAD

**Issue by rLannes** [tanaylab/metacells#1]
Hi, 
First thank you for providing such a package to the community.

I want to use metacells to analyses multi-sample (different patients, different libraries, all 10X)
I wonder if I should **apply a normalization step before importing the matrix?**

I would like to know  **can I color cells based on samples of origins?** For what I have seen in the documentation cells can only be colored accordingly to metacells or genes expressions.

For the cell/metacells/graph plot is there a way to access the layout: cells position, metacells position and link? So it is easier to customize and tweak?

**Comment by orenbenkiki** [comment]
Hi,

Sorry for the late response. We are finalizing the paper and the package so *do not use it for real-world analysis yet*.

To your questions:

* No, you shouldn't normalize the data, we deal with this internally in the package (mainly by downsampling).
* If you run the umap computation functions, the coordinates are stored as per-observation `umap_x`, `umap_y` annotations in the metacells annotated data object. Likewise theres a per-observation-pair `obs_outgoing_weights` sparse matrix containing the graph used for UMAP. Note *this graph and projection are only for visualization and should not be used for actual analysis*.
