### ISSUE TITLE
Issue with pip install metacells 

### ISSUE THREAD

**Issue by BastLem** [tanaylab/metacells#11]
Hi, 

I have an issue to install metacells with pip : 
**Input** 
pip install metacells  
**Output** 
ERROR: Could not find a version that satisfies the requirement metacells (from versions: none)
ERROR: No matching distribution found for metacells

Do you have an idea to fix this? 
Thank you

**Comment by orenbenkiki** [comment]
Can you say something about what system you are running on? operating system, version of python, etc.?

**Comment by BastLem** [comment]
I'm running on Ubuntu 18.04 and Python 3.6

![Python_version](https://user-images.githubusercontent.com/66820750/134884947-16ce927f-41e8-49c4-9e9c-5dcd0b066e5b.png)
![Ubuntu_Version](https://user-images.githubusercontent.com/66820750/134884975-7b1f6199-377b-464c-81d1-f2cfbd00839f.png)

**Comment by orenbenkiki** [comment]
The package requires python 3.7 or newer. You’ll need to update your python version (the current latest is 3.9). For example, sudo apt install python3.9 (or 3.8, or 3.9).

**Comment by AlexAdrian-Hamazaki** [comment]
I had the same issue. It was resolved by upgrading my pip
