### ISSUE TITLE
Illegal instruction  (core dumped)  in bash script

### ISSUE THREAD

**Issue by onionpork** [tanaylab/metacells#12]
Hey there,

I have a problem for mc.pl.analyze_clean_genes(). 
I run it fine in JupyterNotebook, and also fine if do 'python test_meta.py'. Test_meta.py is basically Metacells_Vignette script. 

But, when I submit .sh  to request 36 cores. 
When it goes to mc.pl.analyze_clean_genes(), it shows Illegal instruction  (core dumped)  as error. 
Do you have any idea why?

Thank you very much for your help!
Best,

**Comment by orenbenkiki** [comment]
Not sure what you mean by "request 36 cores".
*If* this refers to the amount of threads you allow MC2 to use,
then maybe the problem is that the system is running out of memory?
To test this, run the script,
and in another terminal have `top` (or better yet, `htop`) running in parallel,
and keep an eye on the amount of memory used by the system as a whole,
and by your process in particular.

**Comment by onionpork** [comment]
Hi, 

Thank you so much for the quick response. 
I first checked the mem - currently is 206G/503G. 
Then I removed thread request. I did those as follows:

1. qlogin 
2. conda activate
3. python test_meta_step1.py
Print out the step by step
""""""
Start
Load Library
(163234, 32738)
identify excluded_gene_names
before analyze_clean_genes
Illegal instruction (core dumped)
""""""
The 'Illegal instruction (core dumped)' is due to mc.pl.analyze_clean_genes.

I also did save clean.h5ad when I run it directly in JupyterNotebook
But then mc.pl.divide_and_conquer_pipeline also returns the same error, which is the one requests 28 cores based on your  vignette. 

###
I am working on the a Linux cluster that runs a 64-bit CentOS 7.6 operating system with SGE 8.6.4 job scheduler and it is managed using Ansible.

My conda list is shown as below:

_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
anndata                   0.7.6                    pypi_0    pypi
argon2-cffi               21.1.0                   pypi_0    pypi
arpack                    3.7.0                hc6cf775_2    conda-forge
attrs                     21.2.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    4.1.0                    pypi_0    pypi
bottleneck                1.3.2            py39hdd57654_1  
brotli                    1.0.9                he6710b0_2  
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_0    conda-forge
cffi                      1.14.6                   pypi_0    pypi
clustviz                  0.0.6b0                  pypi_0    pypi
cycler                    0.10.0           py39h06a4308_0  
cython                    0.29.24                  pypi_0    pypi
daal                      2020.3             ha770c72_304    conda-forge
daal4py                   2020.3.1         py39h256e257_0    conda-forge
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.4.1            py39h295c915_0  
decorator                 5.1.0              pyhd3eb1b0_0  
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.3              py39h06a4308_0  
expat                     2.4.1                h2531618_2  
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.69.1               h5202010_0  
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      3.4.0                    pypi_0    pypi
hdbscan                   0.8.27                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
igraph                    0.9.4                ha184e22_0    conda-forge
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        4.8.1                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350  
ipykernel                 6.4.1            py39h06a4308_1  
ipython                   7.27.0           py39hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5                    pypi_0    pypi
jedi                      0.18.0           py39h06a4308_1  
jinja2                    3.0.2                    pypi_0    pypi
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9d                   h7f8727e_0  
jsonschema                4.0.1                    pypi_0    pypi
jupyter_client            7.0.1              pyhd3eb1b0_0  
jupyter_core              4.8.1            py39h06a4308_0  
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
kiwisolver                1.3.1            py39h2531618_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
leidenalg                 0.8.7            py39he80948d_0    conda-forge
libblas                   3.9.0            11_linux64_mkl    conda-forge
libcblas                  3.9.0            11_linux64_mkl    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
liblapack                 3.9.0            11_linux64_mkl    conda-forge
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h7f8727e_2  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
llvmlite                  0.37.0                   pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
metacells                 0.5                      pypi_0    pypi
metis                     0.2a5                    pypi_0    pypi
metis-python              0.1                      pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.2            py39h51133e4_0  
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpi                       1.0                       mpich  
mpich                     3.3.2                hc856adb_0  
munkres                   1.1.4                      py_0  
natsort                   7.1.1                    pypi_0    pypi
nbclient                  0.5.4                    pypi_0    pypi
nbconvert                 6.2.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.5                      pypi_0    pypi
notebook                  6.4.4                    pypi_0    pypi
numba                     0.54.1                   pypi_0    pypi
numexpr                   2.7.3            py39h22e1b3c_1  
numpy                     1.20.3           py39hf144106_0  
numpy-base                1.20.3           py39h74d4b33_0  
olefile                   0.46               pyhd3eb1b0_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0                     pypi_0    pypi
pandas                    1.3.3            py39h8c16a72_0  
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.2              pyhd3eb1b0_0  
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.3.1            py39h2c7a002_0  
pip                       21.2.4           py39h06a4308_0  
prometheus-client         0.11.0                   pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyclustering              0.10.1.2                 pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0  
pynndescent               0.5.4                    pypi_0    pypi
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-graphviz           0.13.2                   pypi_0    pypi
python-igraph             0.9.6            py39hfef886c_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pyzmq                     22.2.1           py39h295c915_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
scanpy                    1.8.1                    pypi_0    pypi
scikit-learn              0.24.2           py39ha9443f7_0  
scikit-learn-intelex      2021.2.1         py39hf3d152e_1    conda-forge
scipy                     1.7.1            py39h292c36d_2  
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                58.0.4           py39h06a4308_0  
sinfo                     0.3.4                    pypi_0    pypi
sip                       4.19.13          py39h2531618_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
statsmodels               0.13.0                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
suitesparse               5.10.1               hd8046ac_0    conda-forge
tables                    3.6.1                    pypi_0    pypi
tbb                       2020.2               h4bd325d_4    conda-forge
terminado                 0.12.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.11               h1ccaba5_0  
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.0              pyhd3eb1b0_0  
tzdata                    2021a                h5d7bf9c_0  
umap-learn                0.5.1                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
widgetsnbextension        3.5.1                    pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0
###

Many thanks for any suggestion.

**Comment by orenbenkiki** [comment]
The vignete used 28 cores just because that's what happened to be available on my machine at the time; there's nothing special about this number.

I'm assuming that you installed the binary wheel for MC2 using pip, and that your machine supports AVX2?

I'm a bit confused about what does and what doesn't work. Originally you said that `python test_meta_step1.py` worked, unless you tried to use 35 cores (how many does your machine have, BTW - by default the code will use all of them); now it seems it doesn't work even if you remove the threads request?

Finally, the fact that now your machine already uses 200GB out of 500GB doesn't mean anything about how much memory was used during the execution of the script - one has to keep an eye open (using `top` or `htop` or the like) during the execution. Looking at it before/after the execution doesn't say much (well, except that the script has "only" 300GB to play with before the OS will kill it).

**Comment by onionpork** [comment]
Thank you so much for your prompt reply.  

The total memory of cluster I previously allocated is too small. Now, I change to a 1T cluster. It works fine now. 

Many thanks.
