### ISSUE TITLE
Number of metacells generated

### ISSUE THREAD

**Issue by yuhanH** [tanaylab/metacells#18]
Hi, 
Is there a way to determine the number of metacells generated by `divide_and_conquer_pipeline`?

**Comment by orenbenkiki** [comment]
Intentionally no.

You should not expect the number of metacells to be the number of cell types or anything like that. The metacells concept is to have as many as possible metacells, as long as we get a reliable estimate of gene expression levels in each one, and then annotate these metacells with cell types (using various techniques, clustering being one).

That said, playing with the `target_metacell_size` will increase/decrease the size (and therefore the amount) of metacells. The default aims at ~160K UMIs per metacell (there's also a minimum of 12 cells per metacell); playing with this might make sense for specific data sets, but should be done with care.

**Comment by yuhanH** [comment]
Thanks for your rapid reply. Very helpful!
