### ISSUE TITLE
Keep track of cell barcodes that end up in a metacell

### ISSUE THREAD

**Issue by tzeitim** [tanaylab/metacells#19]
Is there any native function of the package to keep lists of the cell barcodes that constitute a metacell?

I can think of using the `.uns` portion of the `anndata` object for a manual implementation but I was wondering if the package already supports this type of operation.

**Comment by orenbenkiki** [comment]
In the cells annotated data there is a `metacell` per-observation annotation, so you can identify which cell goes into which metacell. Presumably, there is also a `barcode` or `name` or whatever per-observation property, so you can track this as well.
