### ISSUE TITLE
error when calling mc.pl.relate_genes()

### ISSUE THREAD

**Issue by hurleyLi** [tanaylab/metacells#3]
Hi,
When calling `mc.pl.relate_genes(clean)` I got this error
```
assert utt.is_canonical(data)
AssertionError: 
```

I'm able to run through the tutorial dataset with no problem, but somehow my own dataset got this error. Could you please let me know what might cause an AnnData object not "canonical" and what's the best way to check. 

Thanks!
Hurley

**Comment by orenbenkiki** [comment]
https://metacells.readthedocs.io/en/latest/utilities.html#metacells.utilities.typing.is_canonical says:

> Return whether the data is in canonical format.
>
> For numpy matrices or vectors, this means the data is contiguous (for matrices, in either row-major or column-major order).
>
> For sparse matrices, it means the data is in COO format, or compressed (CSC or CSR format), with sorted indices and no duplicates.
>
> In general, we’d like all the data stored in AnnData to be canonical.

That said, I'm replacing all calls to `assert is_canonical(...)` to a new `mustbe_canonical(...)` function which will give a more detailed assertion failure, giving the exact reason the data is not canonical. Will be in the upcoming release.

Speaking of which - we haven't _quite_ released the code for general usage yet. The 0.4.* versions are still basically internal releases. I hope to properly release an 0.5 version (together with uploading the accompanying paper etc.)

**Comment by hatran22** [comment]
I also have a somewhat similar issue:
[AssertionError: non-canonical sparse matrix: might have duplicate indices]()

**Comment by orenbenkiki** [comment]
In general this means that the X matrix of the data is in sparse format and was obtained by performing some operations that could potentially have created duplicated or unordered indices. You need to call scipy sort_indices and/or sum_duplicates on this data to bring it to the "canonical" format.
