### ISSUE TITLE
compute_for_mcview() computes gene-gene similarity without normalization

### ISSUE THREAD

**Issue by orenmn** [tanaylab/metacells#34]
Currently (if I understand correctly) `pipeline.compute_for_mcview()` computes gene-gene similarity without first normalizing to the total number of UMIs per metacell.

**Comment by orenbenkiki** [comment]
In the-about-to-be-released version 0.9 `compute_for_mcview` works on fractions so there's no issue there.

**Comment by orenbenkiki** [comment]
Version 0.9 is now published so closing this as done.
