### ISSUE TITLE
AttributeError: partially initialized module 'metacells' has no attribute 'ut'

### ISSUE THREAD

**Issue by imet-k** [tanaylab/metacells#38]
When I run the code I get this message
AttributeError: partially initialized module 'metacells' has no attribute 'ut'

**Comment by orenbenkiki** [comment]
That's strange - sounds like an issue with cyclical imports. But this doesn't happen to anyone else so you must be doing something different.

Are you using v0.8 (from `pip install`) or the latest version from git?

Do you see the problem if you just `import metacells` without anything else? If this only happens with "some other stuff" I'd look at this other stuff for cyclical import issues.

**Comment by imet-k** [comment]
Thank you for getting back to me so quickly. 
This is my pip version
pip 20.2.1 from /home/kadi/.local/lib/python3.8/site-packages/pip (python 3.8)

and I only imported metacells and anndata. 
This is my code:

```
import metacells as mc
import anndata as ad
raw = ad.read_h5ad('data.h5ad')
mc.ut.set_name(raw, 'Spleen')
print(raw.shape)

```

**Comment by orenbenkiki** [comment]
And just to make sure, you just did `pip install metacells`, correct?

If so, this is very strange. It isn't "it works for me", it's "it works for everyone else". I can suggest uninstalling and re-installing metacells but that's just grasping at straws.

**Comment by imet-k** [comment]
Thank you very much. The problem is solved. I run the code in another folder. There was _pycash_ in the old one and I don't know if it was causing some problem.
