### ISSUE TITLE
Installation error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by UboCA** [tanaylab/metacells#39]
Hi, 
I tried to install metacells in a linux machine but got errors as followed.
![image](https://user-images.githubusercontent.com/69028068/219655550-225bb6d5-bdaa-4432-9068-14a082dfd93c.png)

Could you tell me whether this console fit for installation of metacells?

Also, clang and gxx had been prepared for compile it naively.

Other info maybe useful:
- Python version : 3.9.5
- Linux machine info: Linux version 5.4.0-132-generic (buildd@lcy02-amd64-059) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))

**Comment by orenbenkiki** [comment]
Hmmm. Can you try `pip install --debug`, perhaps that would make the problem clearer. I'm not sure what this `--native` flag is - who gives it to whom - it doesn't appear in my `setup.py` script.

**Comment by UboCA** [comment]
Thanks, I have successfully installed it in a new conda env(python=3.10.9). 
Maybe above error occured by some pre-existing dependencies conflict.
