### ISSUE TITLE
combining datasets

### ISSUE THREAD

**Issue by cartographerJ** [tanaylab/metacells#4]
In the example data, you use a matrix of concatenated experiments and then find meta cells. Is it possible to do this the opposite way and find meta cells in each dataset individually and then concatenate the metacells into a single dataset?

**Comment by orenbenkiki** [comment]
In principle you could run the metacells algorithm on each cells data set, then concatenate the resulting metacells data sets. However this would be sub-optimal. Running the algorithm on the combined cells should give you better sensitivity in detecting rate cell types, and in sampling points along a gradient between cell states (dynamic processes).
