### ISSUE TITLE
QC Metrics

### ISSUE THREAD

**Issue by AlexAdrian-Hamazaki** [tanaylab/metacells#43]
Hello, I'm currently trying out Metacell2.

The paper talks about QC metrics near the end. There is mention of test to identify if the UMI vectors in one given metacell are coming from the same multinomial distribution. There also seems to be some normalization for metacell size.

Is there a function in MC2 to visualize the results of these tests for the final metacell classifications?

I also saw that you are working on a vignette to explore how to do the suggested iterations of "adding/removing forbidden genes"

Is there any other QC metrics that are suggested?

Thanks

**Comment by orenbenkiki** [comment]
"It's complicated"

* Version 0.9 (which we are finalizing now) is different from version 0.8 (see the project README). I'm working on an updated vignette, should (hopefully) be this month.

* We have the [MCView](https://github.com/tanaylab/MCView) project for visualizations.

**Comment by orenbenkiki** [comment]
Version 0.9 is now published, together with the vignettes, which go into more detail into QC measures and in general the iterative process one "should" use to get high-quality MCs. Closing this in the hope this suffices.
