### ISSUE TITLE
[compilation not working] install option native not found

### ISSUE THREAD

**Issue by blackTay** [tanaylab/metacells#44]
The following has happened on both linux machines that we have tried.

When running the pip install metacells command, the installation seems to work fine but upon including metacells in python, it instructs to re-compile:

> ImportError: The metacells precompiled wheel is using AVX2 FMA instructions.
> However, AVX2 FMA is not available on this computer's processors.
> You can avoid the wheel using: pip install metacells --install-option=--native
> This will compile the metacells package on and for this computer's processors.

However, metacells does not recognise the install the advertised install option. 
In particular, 
`pip install metacells --install-option=--native`
leads to

 error: option --native not recognized

<pre><span style="color:#C01C28"> ERROR: Command errored out with exit status 1:</span>
<span style="color:#C01C28">     command: /usr/bin/python3 -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-7yhw1gwn/metacells/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-7yhw1gwn/metacells/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; install --record /tmp/pip-record-bpypaovu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/user/.local/include/python3.8/metacells --native</span>
<span style="color:#C01C28">         cwd: /tmp/pip-install-7yhw1gwn/metacells/</span>
<span style="color:#C01C28">    Complete output (6 lines):</span>
<span style="color:#C01C28">    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]</span>
<span style="color:#C01C28">       or: setup.py --help [cmd1 cmd2 ...]</span>
<span style="color:#C01C28">       or: setup.py --help-commands</span>
<span style="color:#C01C28">       or: setup.py cmd --help</span>
<span style="color:#C01C28">    </span>
<span style="color:#C01C28">    error: option --native not recognized</span>
<span style="color:#C01C28">    ----------------------------------------</span>
<span style="color:#C01C28">ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-7yhw1gwn/metacells/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-7yhw1gwn/metacells/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; install --record /tmp/pip-record-bpypaovu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/user/.local/include/python3.8/metacells --native Check the logs for full command output.</span>
</pre>

Thank you!

The machine processor details are:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       4
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      21
Model:                           2
Model name:                      AMD Opteron(tm) Processor 6376

**Comment by orenbenkiki** [comment]
Pip has changed its flags because "reasons". The flags for forcing or avoiding the use of precompiled wheels changed to `--only-binary <control>` and `--no-binary <control>` and `--prefer-binary <control>`. See `pip install --help` for details.
