### ISSUE TITLE
 Metadata Attribution for scRNAseq Metacells

### ISSUE THREAD

**Issue by fadichoucha** [tanaylab/metacells#45]
Hello,

I have a question regarding the use of metadata for scRNAseq with the newly generated metacells. I recently used Metacells V0.8 to generate the metacells, and then I converted the results to v0.9. In an attempt to visualize and edit the annotation of the results, I used MCView (v0.2.9.9). While I didn't encounter any issues with cell types, I'm currently struggling to attribute metadata information, such as the Tumor sample, to the new metacells (see attached fig, at the bottom: Tumor clustering). I would appreciate any information or ideas on how to accomplish this.

Thank you for your help.

![Gene modules Heatmap](https://github.com/tanaylab/metacells/assets/56047822/15f0259a-189a-4209-91a6-6b27226742e5)

**Comment by orenbenkiki** [comment]
Do you mean how to transfer annotation metadata (such as cemm type annotation) from the old metacells to the new ones?

One way could be to:
- convey_group_to_obs to apply the *old* metacells data to all the cells, and then
- convey_obs_to_group to apply the per-cell data to the *new* metacells

This isn't "great" but it would give you a starting point. You would still need to review the per-new-metacell annotations and correct them where necessary.

**Comment by fadichoucha** [comment]
@orenbenkiki thank you for your response.

I need to transfer annotation metadata from cells meatdata to new metacells.

From your answer I think _convey_obs_to_group_ would help me for that.

**Comment by orenbenkiki** [comment]
Yes, that's the one.
