### ISSUE TITLE
Adding forced genes to feature genes in divide_and_conquer_pipeline

### ISSUE THREAD

**Issue by orimosko** [tanaylab/metacells#46]
Hi,

In metacells.pipeline.feature.extract_feature_data, we can manually add gene names that we want to include as feature genes (forced genes). However, I wasn't able to find a way to add them as part of the divide_and_conquer pipeline. Did I miss the parameter or is this not possible in the unified function?

Thanks!
Ori

**Comment by orenbenkiki** [comment]
In the latest pubished 0.9.*, if you set a `select_gene` mask before calling the divide-and-concquer algorithm, it will force it to use these genes all the time instead of whatever it would have chosen by itself.
