### ISSUE TITLE
noisy genes can be selected for computing similarity

### ISSUE THREAD

**Issue by orenmn** [tanaylab/metacells#49]
the current README.rst says: "Noisy genes are not only forbidden from being selected for computing cells similarity, but are also [...]"

But currently, as far as I can tell, marking a gene as noisy still allows it to be selected.
So the README.rst should be rephrased, but in my opinion the intuitively expected behavior is actually as said in the README. i.e., I would expect you to automatically not allow selecting noisy genes (maybe have an option to explicitly allow a gene to be noisy but still be selected, but not as the default).

If you decide to keep the current behavior, then because it is pretty unintuitive (at least for me), I think the vignettes should also explicitly say something like: "so you probably want to specify noisy genes also as lateral, otherwise they might be selected for computing similarity"

**Comment by orenbenkiki** [comment]
Ugh, a documentation bug. Wasn’t fixed when we separated the concerns. The
vignette documentation is correct though. I’ll fix it.
