### ISSUE TITLE
compute_for_mcview doesn't add mcview_format

### ISSUE THREAD

**Issue by ukleiner** [tanaylab/metacells#51]
Hi,
I'm running [metacells vignette](https://metacells.readthedocs.io/en/latest/Metacells_Vignette.html#further-analysis) (different data, same procedure).
After running `mc.pl.compute_for_mcview(adata=clean, gdata=metacells, random_seed=123456, compute_var_var_similarity=dict(top=50, bottom=50))` the metacells AnnData object doesn't have an additional attribute 'mcview_format' in it's `uns` property and MCView complains about it missing.
I'm running with 
```
import logging
mc.ut.setup_logger(level=logging.DEBUG)
```
And the only logs while `running compute_for_mcview` are
```
~/.local/lib/python3.9/site-packages/umap/umap_.py:1780: UserWarning: using precomputed metric; inverse_transform will be unavailable
  warn("using precomputed metric; inverse_transform will be unavailable")
~/.local/lib/python3.9/site-packages/umap/umap_.py:1780: UserWarning: using precomputed metric; inverse_transform will be unavailable
  warn("using precomputed metric; inverse_transform will be unavailable")
100%|██████████[00:16]
```
Running manually `mc.utilities.set_m_data(metacells, "mcview_format", "1.0")` does add the key to the dict (but MCView stil complains).

Any ideas how to solve? Everything else works as expected

Tnx

**Comment by orenbenkiki** [comment]
Is this the version from pip (0.8) or from the head of github (0.9-dev)?

**Comment by ukleiner** [comment]
Pip version

**Comment by orenbenkiki** [comment]
The updated README w/ all the new fields only applies to 0.9. I've been saying we are "just about to release it" to pip for a while now, but some thigs kept coming up. Right now we plan on releasing it before the end of the month. If nothing else comes up :-)
