### ISSUE TITLE
vignettes for 0.8

### ISSUE THREAD

**Issue by GabyBG** [tanaylab/metacells#52]
Hello, 
I am really excited to try this approach on my sc dataset. I have installed metacells successfully using pip install. Pip installs the version 0.8 I was wondering if you can point me to where the vignettes specific for 0.8 are. I could only find 0.9 examples.

Thank you!

**Comment by orenbenkiki** [comment]
https://metacells.readthedocs.io/

**Comment by GabyBG** [comment]
Thank you so much!
