### ISSUE TITLE
_collect_metacell() performs unweighted geomean for regularization values

### ISSUE THREAD

**Issue by orenmn** [tanaylab/metacells#59]
in `metacells/pipeline/collect.py`, `_collect_metacell()` performs a weighted geomean for the regularized expression (by the way, why not use `scipy.stats.mstats.gmean` with the weights parameter?), yet performs an unweighted geomean for the regularization values, i.e., current code does:
`regularization_of_metacell = ss.mstats.gmean(regularization_per_cell_of_metacell)`
while seems to me the code should be:
`regularization_of_metacell = ss.mstats.gmean(regularization_per_cell_of_metacell, weights=weight_per_cell_of_metacell)`

**Comment by orenbenkiki** [comment]
Should be fixed by commit cea46935f8a29661e0761e8cbbd7fb0afdfa7590 - will be eventually published in 0.9.4.
