### ISSUE TITLE
Displaying Heatmap for Noisy Gene HBB IGKC in Iterative Jupyter Notebook

### ISSUE THREAD

**Issue by UboCA** [tanaylab/metacells#68]
Hi,

I encountered displaying pictures while working with the iterative Jupyter notebook provided in [Iterative Process](https://tanaylab.github.io/metacells-vignettes/iterative.html). I have been unable to display the heatmap for the noisy gene _HBB_ _IGKC_. 
![image](https://github.com/tanaylab/metacells/assets/69028068/f1b87840-a37d-406f-91e9-d9859b12d839)

While the other parts of the notebook function as expected, the heatmap for these specific genes does not load. I am unsure if this is due to a network issue or some other problem on my end.

Furthermore, I have attempted to replicate the data independently. However, I noticed that the results of my dimensionality reduction differ from those in the tutorial. Consequently, I am unable to visualize HBB and IGKC in the inner-fold heatmap by myself.
![image](https://github.com/tanaylab/metacells/assets/69028068/a7b7533a-cb81-42b6-9425-1b6f1feaee8f)

I would be extremely grateful if you could provide the displaying pictures to aid my understanding of noisy gene evaluation. Alternatively, if possible, an update to the notebook to address this issue would be greatly appreciated.

Best,

UboCA

**Comment by tzeitim** [comment]
Regarding the missing images, @UboCA see https://github.com/tanaylab/metacells-vignettes/issues/1 

You are not seeing the images due to some artifacts on how github renders html vs ipynb - just open the notebook instead of the html

**Comment by UboCA** [comment]
> Regarding the missing images, @UboCA see [tanaylab/metacells-vignettes#1](https://github.com/tanaylab/metacells-vignettes/issues/1)
> 
> You are not seeing the images due to some artifacts on how github renders html vs ipynb - just open the notebook instead of the html

Thank you to let me know it, I see it!
