### ISSUE TITLE
metacells2 'unknown mask data: lateral_gene' 

### ISSUE THREAD

**Issue by angelica-varesi** [tanaylab/metacells#70]
Hi, 
I am getting this error: 

  File "../python3.10/site-packages/metacells/tools/mask.py", line 87, in combine_masks
    raise KeyError(f"unknown mask data: {mask_name}")
KeyError: 'unknown mask data: lateral_gene'

when I try to run this code to obtain Metacells
mc.pl.divide_and_conquer_pipeline(raw, random_seed=123456, target_metacell_umis= 80000)

As row I input the counts RNA data in h5ad file. 

I don't know how to solve the issue. 

Thanks a lot for the help!!!!

**Comment by angelica-varesi** [comment]
Thanks!
However, I would like to set it as NULL since I don't want to have any gene excluded. 
Could you please send me the code for that?
Thanks a lot!!!!

**Comment by orenbenkiki** [comment]
Just set it to an all-zero mask (`np.zeros(n_genes, bool)`). Of course it is likely that once you start computing metacells you'll discover that you actually want to mark some genes as literal and re-compute... but that depends on your data set.

**Comment by angelica-varesi** [comment]
Thanks a lot!
Angelica
