### ISSUE TITLE
Why are so many cells excluded? Just left with ~100 metacells

### ISSUE THREAD

**Issue by robertzeibich** [tanaylab/metacells#77]
scanpy QC data: 4749 cells; 33117 genes
exclude cells by UMIs:
![image](https://github.com/user-attachments/assets/db607338-6273-4860-ba76-0a25eba2a74c)
excluded gene names ["XIST", "MALAT1", "NEAT1"]  and patterns ["MT-.*"]  
exclude cells by high excluded gene UMIs: PROPERLY_SAMPLED_MAX_EXCLUDED_GENES_FRACTION = 0.25
![image](https://github.com/user-attachments/assets/9f35ea55-28d6-40f7-a807-61eb701c992b)
extracted the clean data: 3109 cells, 33023 genes
marked recommended lateral genes and lateral gene patterns
marked noisy genes
assigned cells to metacells with devide and conquer
collected the metacells:

set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.obs[grouped]: 115 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.obs[total_umis]: 115 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.layers[total_umis]: ndarray 115 X 33023 float32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.obs[__zeros_downsample_umis]: 115 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.layers[zeros]: ndarray 115 X 33023 int32s
set H19-30-002_10X393_3_HiT_CA4-DGC.cells.obs[metacell_name]: 3109 <U8s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[Biotype]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[Chromosome]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[End]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[Gene]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[Start]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[feature_is_filtered]: 0 true (0%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[feature_name]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[feature_reference]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[feature_biotype]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[feature_length]: 33023 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[gene_id]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[genec_gene_id.v]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[genec_gene_name]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[genec_gene_type]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[genec_gene_id]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[genec_gene_id_version]: 33023 objects
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[n_cells]: 33023 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[mt]: 0 true (0%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[ribo]: 86 true (0.2604%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[n_cells_by_counts]: 33023 int64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[mean_counts]: 33023 float32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[log1p_mean_counts]: 33023 float32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[pct_dropout_by_counts]: 33023 float64s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[total_counts]: 33023 float32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[log1p_total_counts]: 33023 float32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[bursty_lonely_gene]: 0 true (0%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[properly_sampled_gene]: 33023 true (100%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[excluded_gene]: 0 true (0%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[lateral_gene]: 518 true (1.569%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[full_gene_index]: 33023 int32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[noisy_gene]: 15 true (0.04542%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[selected_gene]: 1322 true (4.003%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[rare_gene]: 0 true (0%) out of 33023 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.var[rare_gene_module]: 33023 int32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.obs[metacells_rare_gene_module]: 115 int32s
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.obs[rare_metacell]: 0 true (0%) out of 115 bools
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.uns[outliers]: 118
set H19-30-002_10X393_3_HiT_CA4-DGC.preliminary.metacells.uns[metacells_algorithm]: metacells.0.9.5

115 metacells, 33023 genes

Happy to share the file.

**Comment by orenbenkiki** [comment]
The answer seems to be in the 1st graph. "Will exclude 1640 cells with more than 20000 UMIs." You didn't adjust the limits to fit the data. There's a reason we show these graphs and say you need to tweak these numbers to fit your data ... ;-)

**Comment by robertzeibich** [comment]
Thanks for the quick response. 
I did not exclude cells by UMIs. Now, I am left with n_obs × n_vars = 206 × 33023.
That seems still low.

**Comment by orenbenkiki** [comment]
Starting with <5K cells, getting ~200 MCs, sounds about right - even a bit high. Remember each metacell combines many cells (around 25 in your case).

**Comment by orenbenkiki** [comment]
Also, not sure about not excluding cells by UMIs at all. At least exclude cells with too few UMIs as they are very low quality and will pollute the resulting model.

**Comment by robertzeibich** [comment]
Ok. Is there an easier way to annotate those metacells? MyView seems tedious.

**Comment by orenbenkiki** [comment]
You mean MCView?

I'm afraid I don't have an easy way for you - yet. Gene-gene plots plus understanding of the biology is the current best practice - unless you have an annotated MCs atlas of the relevant biology, in which case, projection will save you a lot of effort. We are actively working on better ways to automatically analyze the data but that's very much WIP.
