### ISSUE TITLE
How to force output obs_outgoing_weights?

### ISSUE THREAD

**Issue by hurleyLi** [tanaylab/metacells#8]
Hi,
I noticed that when I run `divide_and_conquer_pipeline`, sometimes I got `.obsp[obs_outgoing_weights]` output __in the original AnnData (not Metacell AnnData)__, but sometimes I don't, even though I set `mc.pl.set_max_parallel_piles(1)`. I suspect it's because of the size of the dataset? 

I'm wondering if there's any way to force the output of `.obsp[obs_outgoing_weights]` __in the original AnnData__, because I'd like to use that to compare the metacells with single-cells graph built from `obs_outgoing_weights`.
Thanks!
Hurley

**Comment by orenbenkiki** [comment]
Short answer is you can't. Nothing like this is ever computed for a large (multi-pile) data set. Instead, for each two observations (cells) there might be no weight at all ever computed (this is what allows the algorithm to be efficient) or possibly multiple weights computed at different times (if the two cells were both in the same pile more than once during the algorithm).

If your data is small enough you can run the  'compute_direct_metacells` pipeline which will force the code to treat it as a single pile. This would give different results than the divide-and-conquer algorithm though.

In general you really should thinking about the similarity between metacells. Not only would any distance metric between metacells be much more robust, this would also give you 4 orders of magnitude less data so it would be much faster to work with.

This is essentially what we do when we generate a UMAP projection of the metacells, see `  'compute_knn_by_features' and 'compute_umap_by_features' - which are *not* recommended for use for anything other than visualizations.
