### ISSUE TITLE
How to assign celltype for metacells

### ISSUE THREAD

**Issue by ZivTQ** [tanaylab/metacells#80]
Hi
thanks for your work in metacells.
I have some questions:
1. I had run thia step: mc.tl.convey_obs_to_group(
    adata=clean, gdata=metacells,
    property_name="orig.ident", to_property_name="group_name",
    method=mc.ut.most_frequent  # This is the default, for categorical data
)

that means I had got the metacells, right??? 
The next step is to assign celltype in MCView!

However, MCView is not work for, is there have another way?

![1734238409816](https://github.com/user-attachments/assets/959037c2-798b-4369-8e0c-6d8283be4b99)

**Comment by orenbenkiki** [comment]
I don't see an actual error message in the image - calculating the correlations may take a few minutes. If you still have problems with MCView, it is better if you open an issue in https://github.com/tanaylab/MCView, and Aviezer will help you out.
